In [3]:
import numpy as np


CREATING ARRAY FROM LIST

In [6]:
arr_1d = np.array([1,2,3,4,5])
#this fuctions accepts only list

arr_2d = np.array([[1,2,3],[4,5,6]])


print(arr_1d)
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


LIST VS NUMPY ARRAY


In [9]:
py_list = [1,2,3]
print("Python list multiplication : ",str(py_list*2))

numpy_arr = np.array([1,2,3])
print("Numpy array multiplication : ",str(numpy_arr*2))

Python list multiplication :  [1, 2, 3, 1, 2, 3]
Numpy array multiplication :  [2 4 6]


TIME EFFICIENCY

In [12]:
import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("Time required for py_list ",str(time.time()-start))

start = time.time()
numpy_arr = np.array([i*2 for i in range(1000000)])#numpy_arr = np.arrange(1000000)*2
print("Time required for numpy_array ",str(time.time()-start))





Time required for py_list  0.08362841606140137
Time required for numpy_array  0.13461613655090332


CREATING ARRAY FROM SCRATCH

In [8]:
import numpy as np

zeros = np.zeros((3,4))#it creates a n*m array
print("zeros array : \n")
print(zeros)

ones = np.ones((3,4))#it creates a n*m array
print("ones array : \n")
print(ones)

full = np.full((3,4),7)#it creates a n*m array assigning each with the value you want
print("full array : \n")
print(full)

random = np.random.random((3,4))#it creates an n*m array with random numbers
print("random array : \n")
print(random)


sequence = np.arange(0,10,2) #0 to 9 with 2 hops
print("sequence array : \n")
print(sequence)

zeros array : 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array : 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array : 

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
random array : 

[[0.9348448  0.56140542 0.83023305 0.79662681]
 [0.61077363 0.98378893 0.67899179 0.19382198]
 [0.31892672 0.51042041 0.38884401 0.33813937]]
sequence array : 

[0 2 4 6 8]


VECTOR MATRIX AND TENSOR

In [12]:
vector = np.array([1,2,3,4,5])#1D
print(vector)

matrix = np.array([[1,2,3],[4,5,6]])#2D
print(matrix)

tensor = np.array([[[1,2],[4,5]],[[6,7],[8,9]]])#3D
print(tensor)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [4 5]]

 [[6 7]
  [8 9]]]


ARRAY PROPERTIES

In [23]:
arr = np.array([[1,2,3],[4,5,True]])#stores data in same type
print("Shape of array ",arr.shape)
print("dimension ",arr.ndim)
print("size ",arr.size)
print("datatype ",arr.dtype)

Shape of array  (2, 3)
dimension  2
size  6
datatype  int64


ARRAY RESHAPING

In [30]:
arr = np.arange(12)
print(arr)

reshaped_arr = arr.reshape((3,4))
print(reshaped_arr)

flattened = reshaped_arr.flatten()
print(flattened)


#ravel returns view, instead of copy
raveled = reshaped_arr.ravel()
print(raveled)

transepose_arr = reshaped_arr.T
print(transepose_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
