In [1]:
import numpy as np

NUMPY ARRAY OPERATIONS

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing",arr[2:7])# basically limiting the window 7 is exclusive

print("With Step",arr[0:8:2])

print("Negative indexing",arr[-2])


Basic Slicing [3 4 5 6 7]
With Step [1 3 5 7]
Negative indexing 8


FOR 2D SLICING

In [14]:
arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific element",arr_2D[0,2])

print("Specific row ",arr_2D[0])

print("All rows and specific column",arr_2D[:,2])


Specific element 3
Specific row  [1 2 3]
All rows and specific column [3 6 9]


SORTING

In [18]:
arr = np.array([1,9,3,6,5,4,8,8,7,9,1])
print(np.sort(arr))

arr_2D = np.array([[1,3,2],[4,7,1],[9,2,8]])
print("Sort by column ",np.sort(arr_2D,axis=0))
print("Sort by rows ",np.sort(arr_2D,axis=1))

[1 1 3 4 5 6 7 8 8 9 9]
Sort by column  [[1 2 1]
 [4 3 2]
 [9 7 8]]
Sort by rows  [[1 2 3]
 [1 4 7]
 [2 8 9]]


FILTERING ARRAYS

In [24]:
numbers = np.arange(0,10)
print(numbers)
even_numbers = numbers[numbers%2 == 0]
print(even_numbers)



[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


FANCY INDEXING AND np.where()

In [23]:
indices = [0,2,4]
print(numbers[indices])

print(numbers)

where_result = np.where(numbers>5)
print(numbers[where_result])

[0 4 8]
[0 2 4 6 8]
[6 8]


ADDING AND REMOVING DATA

In [25]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.concatenate((arr1,arr2)))

[1 2 3 4 5 6 7 8]


ARRAY COMPATIBILITY


In [29]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10,11,12])
arr3 = np.array([13,14,15,16,17,18])

print("Compatibility shapes",arr1.shape==arr2.shape)


deleted = np.delete(arr1,0)
print(deleted)

Compatibility shapes True
[2 3 4 5 6]
